version: '3'


services:
  django:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    ports:
    - "5000:5000"
    image: davidfischer/ethicaladserver
    container_name: ethicaladserver_django
    env_file:
      - ./.envs/production.env
    command: /start

  # Azure doesn't seem to support inheriting correctly
  celeryworker:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: davidfischer/ethicaladserver
    container_name: ethicaladserver_celeryworker
    env_file:
      - ./.envs/production.env
    command: /start-celeryworker
