# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

jobs:
  tests:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - run: pip install --user requirements/testing.txt
      - run: tox -e py3

  checks:
    docker:
      - image: 'cimg/python:3.6'
        environment:
          NODE_VERSION: 10.17.0
    steps:
      - checkout
      - run: pip install --user requirements/testing.txt
      - run: tox -e migrations
      - run: tox -e lint
      - run: tox -e docs
      - run: tox -e eslint

workflows:
  version: 2
  test:
    jobs:
      - checks
      - tests
